InfoSpot Labels on hover
3200-10/uwa-historical-tour pull request #15
Opened 2020-09-13 12:02 UTC by dodecadumpling

Changes:
css - for the label (not the best, but wanted it to stand out...maybe too much)
pano.js - infoLabel on hover and commented out the previous elements.

2020-09-15 08:26 UTC, Drewbi requested changes

2020-09-15 08:26 UTC, Drewbi commented on src/util/pano.js
> +import { Vector3, IcosahedronBufferGeometry } from 'three'
What is this for?

2020-09-15 08:26 UTC, Drewbi commented on src/util/pano.js
> +    // const infoElement = document.createElement('div')
You can remove these lines if they're no longer being used

2020-09-15 08:26 UTC, Drewbi commented on src/util/pano.js
> +    infoSpot.addHoverElement(infoLabel)
I think we might as well use the inbuilt `setHoverText` since it looks fine and doesn't require making an element. Styling it is a little harder but this is what it looks like out of the box:
<img width="249" alt="Screen Shot 2020-09-15 at 4 23 20 pm" src="https://user-images.githubusercontent.com/38243574/93185461-032e8680-f770-11ea-87e0-ff158543999c.png">

2020-09-15 08:26 UTC, Drewbi commented on src/util/pano.js
> +      this.focus()
This is cool :D

2020-09-16 01:12 UTC, dodecadumpling commented on src/util/pano.js
> +    infoSpot.addHoverElement(infoLabel)
This looks fine, I only wanted to style if we ever run into a problem where white text is harder to read.

2020-09-16 01:13 UTC, dodecadumpling commented on src/util/pano.js
> +      this.focus()
easier to move around, though I hope it doesn't break the side panel click event.

2020-09-16 01:14 UTC, dodecadumpling commented on src/util/pano.js
> +import { Vector3, IcosahedronBufferGeometry } from 'three'
not sure where that came from... maybe it automatically did it when I was playing around with some focus options?

2020-09-16 01:14 UTC, dodecadumpling commented on src/util/pano.js
> +    // const infoElement = document.createElement('div')
will do!

2020-09-16 06:43 UTC, closed without merging